sudo: required
language: cpp
services:
- docker
before_install:
- git config --local user.name "Christoph Stelz"
- git config --local user.email "mail@ch-st.de"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- docker pull cstelz/holmos-build-x86
script:
- docker run -itv $(pwd):/build cstelz/holmos-build-x86
- "./build_appimage.sh"
- mkdir -p /tmp/uploadfiles && cp Holmos_Viewer-x86_64.AppImage /tmp/uploadfiles
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: /tmp/uploadfiles
    on:
        branch: master
