sudo: required
language: cpp
services:
- docker
before_install:
- git config --local user.name "Christoph Stelz"
- git config --local user.email "mail@ch-st.de"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- docker pull cstelz/holmos-build-x86
- docker pull cstelz/holmos-build-x86-win
script:
- docker run -itv $(pwd):/build cstelz/holmos-build-x86
- docker run -itv $(pwd):/build cstelz/holmos-build-x86-win
- "./build_appimage.sh"

after_success:
- mkdir out
- cp Holmos_Viewer-x86_64.AppImage out/Holmos_Viewer-build$TRAVIS_BUILD_NUMBER-x86_64.AppImage
- cp release/gui-qt.exe out/Holmos_Viewer-build$TRAVIS_BUILD_NUMBER-x86_64.exe
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- bash upload.sh out/*

branches:
    except:
        - /^(?i:continuous)$/

