sudo: required
language: cpp
services:
- docker
before_install:
- git config --local user.name "Christoph Stelz"
- git config --local user.email "mail@ch-st.de"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- docker pull cstelz/holmos-build-x86
script:
- docker run -itv $(pwd):/build cstelz/holmos-build-x86
- "./build_appimage.sh"

after_success:
- curl -T Holmos_Viewer-x86_64.AppImage --user $FTP_USER ftp://my.ch-st.de/holmos_viewer/Holmos_Viewer-x86_64-build$TRAVIS_BUILD_NUMBER.AppImage
