sudo: required
language: cpp
services:
- docker
before_install:
- git config --local user.name "Christoph Stelz"
- git config --local user.email "mail@ch-st.de"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- docker pull cstelz/holmos-build-x86
script:
- docker run -itv $(pwd):/build cstelz/holmos-build-x86
- "./build_appimage.sh"
deploy:
  provider: releases
  api_key:
    secure: Uym7J+os0dlmOQxrRN4T4uo/463BST7aHuIYE4ogZWmkWoN5XxMeNNScReKNRUek9YDz8obrrBbGURmynvQ+sBW06BQGFdM1Ec1WfyzkXO0/FdIBx1vArZFAXn/yWZK/ncuX+8F6LkwWMZIiqEblL0GGjk5XihbXZmJZQB6JzK7lkWhX5h6IW+1psMLFNsHNbcf7WqJJ26N/SfJjk0enwquc2E4BMdNPKvX+k2LAOwYmHwkqOxtTwZvh6CCoW96LZZbsRLrjGRTZbbfhK7P3GUIy6R33vc1aAoqVKJ/nhBUcXLAzY+V8x1qX11qakmJM+ImuqItivnyB7purVHMYFHktt3pmnk/CBCd62NhOVcM5XkNjr8Gtao87LUKNF8+4Y6VwAyvOH2oyKw4HEpYK9vjU/EP61ejytQF9o713pW/x2jJdyK43lYPFcliphzqc7lv+53yWK6E8PTSPbNnhj2T9oLcEcuBP7pZ9cN0oQJ2XExFcB1MYc+uYE5UfqpapOWH86xpoo9hKbJ/X3uxWM6S0ORaVoSL1g0qLs0YCdbVAZgV0869hIVGOMIzcf7xfQ/wvIorikTa2lwRdgnBW0D9BWB8ESRvxm/kdtVveJK9kE1E/9Xtjhye5CzZ+nwnclbDHob7z+QivnhGDh3yt9hjqacC2Rkv+4+x68CzSqPQ=
  file: Holmos_Viewer-x86_64.AppImage
  on:
    repo: holmos-frs/gui-qt
