sudo: required

language: cpp

services:
    - docker

before_install:
    - docker pull cstelz/holmos-build-x86

script:
    - docker run -itv $(pwd):/build cstelz/holmos-build-x86
    - ./build_appimage.sh
